default:
  mode: offline
  generate_names: False
  sandbox: '0.0'
  compatibility: forward

offline:
  schema_registry: localhost
  broker: localhost:9092
  registry_url: http://localhost:8081

stream:
  topics:  ('testTopic', 'namesTopic')

consumer:
  topics:
    - 'itpcEvent'

